name: DiGAN
channels:
- pytorch
- defaults
dependencies:
- python=3.6
- pytorch=1.8.0
- scipy
- pip
- pip:
  - dominate==2.4.0
  - torchvision==0.9.0
  - Pillow==7.1.2
  - numpy==1.21.5
  - visdom==0.1.8
  - opencv-python==4.1.0.25
